image:
  file: .gitpod.Dockerfile
tasks:
  - command: red hello.red
ports:
  - port: 6080
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
vscode:
  extensions:
    - red-auto.red@0.3.6:nbKIGnraEz5MxNHzPoio7g==
